spring:
  application:
    name: learning
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${DB_MASTER_URL}
      username: ${DB_MASTER_USER}
      password: ${DB_MASTER_PASSWORD}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${DB_SLAVE_URL}
      username: ${DB_SLAVE_USER}
      password: ${DB_SLAVE_PASSWORD}

mybatis-plus:
  global-config:
    banner: false
    db-config:
      #刷新mapper 调试神器
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      # 大写命名,对表名和字段名均生效
      capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

