services:
  redis-node1:
    image: redis:7.2.5
    container_name: redis-node1
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - ./redis-node1/data:/data
      - ./redis-node1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

  redis-node2:
    image: redis:7.2.5
    container_name: redis-node2
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes:
      - ./redis-node2/data:/data
      - ./redis-node2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

  redis-node3:
    image: redis:7.2.5
    container_name: redis-node3
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
      - "17003:16379"
    volumes:
      - ./redis-node3/data:/data
      - ./redis-node3/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

  redis-node4:
    image: redis:7.2.5
    container_name: redis-node4
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:6379"
      - "17004:16379"
    volumes:
      - ./redis-node4/data:/data
      - ./redis-node4/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

  redis-node5:
    image: redis:7.2.5
    container_name: redis-node5
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:6379"
      - "17005:16379"
    volumes:
      - ./redis-node5/data:/data
      - ./redis-node5/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

  redis-node6:
    image: redis:7.2.5
    container_name: redis-node6
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7006:6379"
      - "17006:16379"
    volumes:
      - ./redis-node6/data:/data
      - ./redis-node6/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge