# 下面配置请看org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 8080
  servlet:
    context-path: /learning
  tomcat:
    uri-encoding: UTF-8
    #一瞬间最大支持的并发的连接数
    max-connections: 10000
    #等待队列长度
    accept-count: 200
    relaxed-Query-Chars:
      - '{'
      - '}'
    threads:
      # 最大工作线程数量。如果启用了虚拟线程，则没有效果。 默认值=200
      max: 300
      # 最小工作线程数量。如果启用了虚拟线程，则没有效果。 默认值=10
      min-spare: 15
      # 线程池支持队列的最大容量。此设置仅在值大于0时有效。 默认值=2147483647
      max-queue-capacity: 2147483647
  compression:
    enabled: true
    mime-types: application/json
    # 压缩所需的最小内容大小（以字节为单位）
    min-response-size: 512

spring:
  application:
    name: learning-combiner
  profiles:
    active: @env@
  data:
    redis:
      password: ${REDIS_PASSWORD}
      # 集群模式下 全局连接池配置无效故删除
      cluster:
        nodes: ${REDIS_NODES}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write_enums_using_to_string: true
  config:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${DATASOURCE_URL}
      username: ${DATASOURCE_USER}
      password: ${DATASOURCE_PASSWORD}
      pool-size: 20
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: ${DB_MASTER_URL}
        username: ${DB_MASTER_USER}
        password: ${DB_MASTER_PASSWORD}
        pool-size: ${spring.datasource.pool-size}
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: ${DB_SLAVE_URL}
        username: ${DB_SLAVE_USER}
        password: ${DB_SLAVE_PASSWORD}
        pool-size: ${spring.datasource.pool-size}

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    banner: false
    db-config:
      # 全局逻辑删除字段名
      logic-delete-field: deleted
      # 逻辑已删除值
      logic-delete-value: now()
      # 逻辑未删除值
      logic-not-delete-value: 'null'
  configuration:
    # 启用从经典数据库列名A_column到驼峰大小写经典Java属性名aColumn的自动映射
    map-underscore-to-camel-case: true
    # 设置驱动程序等待数据库响应的秒数
    default-Statement-Timeout: 5
    # 是否开启二级缓存 非session级别的缓存
    cache-enabled: false


mock:
  account:
    name: xiaoru
    user-id: 646327412
  # sha256后再base64 原'secret-key'
  private-key: hdvhXXXvkwjHrg8zx6MkzG9L9Rmi7S8wJ70zwUCk+ao=

file:
  path: ${file.path}

