

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    pool-size: 20
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${DB_MASTER_URL}
      username: ${DB_MASTER_USER}
      password: ${DB_MASTER_PASSWORD}
      pool-size: ${spring.datasource.pool-size}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${DB_SLAVE_URL}
      username: ${DB_SLAVE_USER}
      password: ${DB_SLAVE_PASSWORD}
      pool-size: ${spring.datasource.pool-size}


mybatis-plus:
  global-config:
    banner: true
  configuration:
    # mysql该配置好像失效的
    default-fetch-size: 100
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl