

mybatis-plus:
  global-config:
    banner: false
  configuration:
    # mysql该配置必须是-2147483648才能启动流式查询
    # 详情请查看https://github.com/baomidou/mybatis-plus/issues/6485
    default-fetch-size: -2147483648